# Python Review

### Difference between Series and DataFrame

- Series is a 1 Dimensional labeled array. Example: A column in Excel or a column in a DataFrame
https://pandas.pydata.org/docs/reference/series.html

- DataFrame is a 2-Dimensional labeled data structure. Example: A table with rows and columns
https://pandas.pydata.org/docs/reference/frame.html

In [1]:
import pandas as pd

In [ ]:
#Example of creating a Pandas Series
#example_list is a list of data values
example_list = ["DS1", "DS2", "DS3", "DS4", "DS5"]
index = [0, 1, 2, 3, 4]
s = pd.Series(data=example_list, index=index)
s

0    DS1
1    DS2
2    DS3
3    DS4
4    DS5
dtype: object

In [ ]:
s[0]

'DS1'

In [ ]:
#Example of creating a Pandas DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [ ]:
#Return a Series representing the 'Name' column
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [ ]:
df['Name'].shape

(3,)

In [ ]:
#Return a DataFrame with only the 'Name' and 'Age' columns
df[['Name', 'Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df[['Name']]

      Name
0    Alice
1      Bob
2  Charlie

In [ ]:
df[['Name']].shape

(3, 1)

In [ ]:

df = pd.DataFrame({'A':[1,2,3], 'B':[4,5,6]})
s = df['A']

print("Mean from a Dataframe:")   # works → returns mean per column
print(df.mean())

print("\nMean from a Series for column A only:")    # works → returns scalar
print(s.mean())

Mean from a Dataframe:
A    2.0
B    5.0
dtype: float64

Mean from a Series for column A only:
2.0

## Data Input

Sample Dataset Resource:
https://public.tableau.com/app/learn/sample-data

Pandas library can read many input types: Flat file (csv, fwf, ...), Excel file, JSON, HTML, XML, Parquet, Latex, SQL, BigQuery. In this session, let's review some popular format that we work in Python.

In [ ]:
#Input a CSV file
csv_input = pd.read_csv(r"C:\Users\LeLuu\Documents\Python_Practice\Python_Review\Data\enigma-us.gov_.census.csv")

In [ ]:
#Display first 2 rows of the dataframe
csv_input.head(2)

,per_idx,per_name,cat_idx,cat_code,cat_desc,cat_indent,dt_idx,dt_code,dt_desc,dt_unit,et_idx,et_code,et_desc,et_unit,geo_idx,geo_code,geo_desc,is_adj,val,serialid
0,1,1963-01-01,1,SOLD,New Single-family Houses Sold,0,5,MEDIAN,Median Sales Price,DOL,0,NaN,NaN,NaN,1,US,United States,0,17200.0,1
1,1,1963-01-01,1,SOLD,New Single-family Houses Sold,0,2,NOTSTD,Houses that are Not Started,K,0,NaN,NaN,NaN,1,US,United States,0,9.0,2

In [ ]:
#Input an Excel file
# (.xls format requires 'xlrd' package to be installed) => Old Excel format from Excel 97-2003
!pip install xlrd
excel_input = pd.read_excel(r"C:\Users\LeLuu\Documents\Python_Practice\Python_Review\Data\sample_-_superstore.xls")

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: xlrd in c:\users\leluu\appdata\local\programs\python\python312\lib\site-packages (2.0.2)

In [ ]:
#Display first 2 rows of the dataframe
excel_input.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [ ]:
#Input an Excel file (.xlsx format) => New Excel format from Excel 2007 and later
!pip install openpyxl
xlsx_input = pd.read_excel(r"C:\Users\LeLuu\Documents\Python_Practice\Python_Review\Data\world_cup_results.xlsx")

Requirement already satisfied: openpyxl in c:\users\leluu\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\leluu\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
#Display first 2 rows of the dataframe
xlsx_input.head(2)

,Year,Date,Time,Round,Stadium,City,Country,HomeTeam,HomeGoals,AwayGoals,AwayTeam,Observation
0,1930,1930-07-13,15:00,Group 1,Pocitos,Montevideo,Uruguay,France,4,1,Mexico,
1,1930,1930-07-13,15:00,Group 4,Parque Central,Montevideo,Uruguay,USA,3,0,Belgium,

In [ ]:
#Read the JSON file
#Be careful with the JSON structure before reading it in pandas
#Make sure to normalize the JSON data first if there are nested structures
#Need to use json.loads() and pd.json_normalize() functions to flatten the data
#Hint: find all dictionaries and lists in the JSON structure

#Step 1: Load JSON data using json.load()
import json
with open(r"C:\Users\LeLuu\Documents\Python_Practice\Python_Review\Data\Sales.json") as f:
    data = json.load(f)

In [ ]:
data

{'store': {'store_id': 'A101',
  'location': {'city': 'New York', 'state': 'NY'},
  'employees': [{'id': 1, 'name': 'Alice', 'role': 'Manager'},
   {'id': 2, 'name': 'Bob', 'role': 'Cashier'},
   {'id': 3, 'name': 'Charlie', 'role': 'Sales Associate'}]},
 'sales': [{'date': '2025-10-01',
   'items': [{'product': 'Laptop', 'quantity': 2, 'price': 1200.0},
    {'product': 'Mouse', 'quantity': 5, 'price': 25.5}]},
  {'date': '2025-10-02',
   'items': [{'product': 'Keyboard', 'quantity': 3, 'price': 75.0},
    {'product': 'Monitor', 'quantity': 1, 'price': 250.0}]}]}

In [ ]:
#check the type of data
type(data)

dict

In [ ]:
#Step 2: Normalize the JSON data (Flatten the data if needed)
#Dictionary is in the store -> employees
#json_normalize(data, record_path, meta)
#Data: is the unserialized JSON objects
#record_path: path to the list of records to be flattened (dictionary inside a list)
#meta: list of paths to get metadata for each record in the record_path
df_employees = pd.json_normalize(data['store'],
                                 meta=[['location','city'],['location','state'],'store_id'],
                                 record_path=['employees'])

#Dictionary is in the sales -> items
df_sales = pd.json_normalize(data['sales'],
                             meta=['date'],
                             record_path=['items'])

In [ ]:
df_employees.head()

   id     name             role location.city location.state store_id
0   1    Alice          Manager      New York             NY     A101
1   2      Bob          Cashier      New York             NY     A101
2   3  Charlie  Sales Associate      New York             NY     A101

In [ ]:
df_sales.head()

    product  quantity   price        date
0    Laptop         2  1200.0  2025-10-01
1     Mouse         5    25.5  2025-10-01
2  Keyboard         3    75.0  2025-10-02
3   Monitor         1   250.0  2025-10-02

## Writing data
df.to_csv() or df.to_excel()

## Exploring Data

### Viewing Data
- df.head(n=?): Return the first n rows for the object based on position. (Same as Sample tool in Alteryx)
- df.tail(n=?): Return the  last n rows from the object based on position.
- df.info(): Print info of all columns contains Column name, Non-Null Count, data types
- df.describe(): print descriptive stats
- df.shape: to output a tuple of array dimension contains number of row and number of cols
- df.size: count how elements in the object = num_rows * num_cols

In [ ]:
xlsx_input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         852 non-null    int64
 1   Date         852 non-null    datetime64[ns]
 2   Time         852 non-null    object
 3   Round        852 non-null    object
 4   Stadium      852 non-null    object
 5   City         852 non-null    object
 6   Country      852 non-null    object
 7   HomeTeam     852 non-null    object
 8   HomeGoals    852 non-null    int64
 9   AwayGoals    852 non-null    int64
 10  AwayTeam     852 non-null    object
 11  Observation  852 non-null    object
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 80.0+ KB

In [ ]:
df_sales.describe()

       quantity        price
count  4.000000     4.000000
mean   2.750000   387.625000
std    1.707825   550.079597
min    1.000000    25.500000
25%    1.750000    62.625000
50%    2.500000   162.500000
75%    3.500000   487.500000
max    5.000000  1200.000000

In [ ]:
xlsx_input.shape

(852, 12)

In [ ]:
#852*12
xlsx_input.size

10224

### Checking Data Types
- df.dtypes: to check data types of each column in the dataframe
- df.select_dtypes(include/exclude = ['List of the data types']): return a subset of dataframe's column based on the column data types

In [ ]:
xlsx_input.dtypes

Year                    int64
Date           datetime64[ns]
Time                   object
Round                  object
Stadium                object
City                   object
Country                object
HomeTeam               object
HomeGoals               int64
AwayGoals               int64
AwayTeam               object
Observation            object
dtype: object

In [ ]:
xlsx_input.select_dtypes(include=['int64'])

     Year  HomeGoals  AwayGoals
0    1930          4          1
1    1930          3          0
2    1930          2          1
3    1930          3          1
4    1930          1          0
..    ...        ...        ...
847  2014          0          0
848  2014          1          7
849  2014          0          0
850  2014          0          3
851  2014          1          0

[852 rows x 3 columns]

### Renaming Columns
df.rename(columns={'Old_Column_Name':'New_Column_Name'}, inplace=True) to rename a column, put in a dictionary of the old column name is the key and the new column name is the value. Inplace=True to modify DataFrame

In [ ]:
xlsx_input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         852 non-null    int64
 1   Date         852 non-null    datetime64[ns]
 2   Time         852 non-null    object
 3   Round        852 non-null    object
 4   Stadium      852 non-null    object
 5   City         852 non-null    object
 6   Country      852 non-null    object
 7   HomeTeam     852 non-null    object
 8   HomeGoals    852 non-null    int64
 9   AwayGoals    852 non-null    int64
 10  AwayTeam     852 non-null    object
 11  Observation  852 non-null    object
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 80.0+ KB

In [ ]:
xlsx_input.rename(columns={'HomeGoals':'HomeGoals_Scrore'}, inplace=True)

In [ ]:
xlsx_input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              852 non-null    int64
 1   Date              852 non-null    datetime64[ns]
 2   Time              852 non-null    object
 3   Round             852 non-null    object
 4   Stadium           852 non-null    object
 5   City              852 non-null    object
 6   Country           852 non-null    object
 7   HomeTeam          852 non-null    object
 8   HomeGoals_Scrore  852 non-null    int64
 9   AwayGoals         852 non-null    int64
 10  AwayTeam          852 non-null    object
 11  Observation       852 non-null    object
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 80.0+ KB

### Indexing and Selection
Loc is based on the **Label** for row name, column name
- loc[] allows the input is a single label, a ilst, a slice object
- If selecting one row df.loc[<index_name>]
- selecting multiple rows df.loc[[<list_of_index>]]
- selecting multiple rows and specified columns: df.loc[[<list_of_index or a_range_if_idx_is_integer>],[<list_of_columns>]]
- selecting a subset of data with condition: df.loc[df['column_name']>0,[<list_of_columns>]]
- for mult-conditions: df.loc[(df['column_name']>0) & (df['column_name']=='abc'),[<list_of_columns>]]

In [ ]:
excel_input.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
#Set index is the Order ID column
excel_input.set_index('Order ID', inplace=True)

In [ ]:
excel_input.head()

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
CA-2016-152156,1,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
CA-2016-152156,2,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
CA-2016-138688,3,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
US-2015-108966,4,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
US-2015-108966,5,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
#Selecting row with index label 1 => showing all columns for that row
excel_input.loc['CA-2016-152156']

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
CA-2016-152156,1,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
CA-2016-152156,2,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [ ]:
#Select multiple rows by passing a list of index
excel_input.loc[['CA-2016-138688','CA-2016-152156']]

,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Order ID,,,,,,,,,,,,,,,,,,,,
CA-2016-138688,3,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714
CA-2016-152156,1,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
CA-2016-152156,2,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [ ]:
#Select a range of rows from 0 to 2 for 3 columns: 'Order ID', 'Sales', 'Profit'
excel_input.loc[['CA-2016-152156','CA-2016-152156','CA-2016-138688'],['Sales','Profit']]

                 Sales    Profit
Order ID
CA-2016-152156  261.96   41.9136
CA-2016-152156  731.94  219.5820
CA-2016-152156  261.96   41.9136
CA-2016-152156  731.94  219.5820
CA-2016-138688   14.62    6.8714

In [ ]:
#Can be used to filter data with condition
excel_input.loc[excel_input['Profit']>0,['Sales','Profit']]

                  Sales    Profit
Order ID
CA-2016-152156  261.960   41.9136
CA-2016-152156  731.940  219.5820
CA-2016-138688   14.620    6.8714
US-2015-108966   22.368    2.5164
CA-2014-115812   48.860   14.1694
...                 ...       ...
CA-2014-110422   25.248    4.1028
CA-2017-121258   91.960   15.6332
CA-2017-121258  258.576   19.3932
CA-2017-121258   29.600   13.3200
CA-2017-119914  243.160   72.9480

[8058 rows x 2 columns]

In [ ]:
#Multiple conditions and select specific columns
excel_input.loc[(excel_input['Profit']>0) & (excel_input['Sales']>500),['Sales','Profit']]

                   Sales    Profit
Order ID
CA-2016-152156   731.940  219.5820
CA-2014-115812   907.152   90.7152
CA-2014-115812  1706.184   85.3092
CA-2014-115812   911.424   68.3568
CA-2014-105893   665.880   13.3176
...                  ...       ...
CA-2016-129630  2799.960  944.9865
CA-2014-143371   998.820   29.9646
CA-2017-121559  1925.880  539.2464
CA-2017-121559  2405.200  793.7160
CA-2017-153871   735.980  331.1910

[883 rows x 2 columns]

iloc is based on the **Integer Position** from **0 to length-1**, but also a boolean array
- With an integer input to select 1 row
- To select multiple rows: df.iloc[[<list_of_integer_position_indx>]] or df.iloc[<a_range_of_indx>]
- can index both axes: df.iloc[0,1] or df.iloc[[0,2],[1,5]] or df.iloc[[0:3],[2:6]]
- CANNOT filter the data with condition because iloc is integer position base, not for boolean conditions

In [ ]:
excel_input.reset_index(inplace=True)

In [ ]:
excel_input.iloc[1]

Order ID                                            CA-2016-152156
Row ID                                                           2
Order Date                                     2016-11-08 00:00:00
Ship Date                                      2016-11-11 00:00:00
Ship Mode                                             Second Class
Customer ID                                               CG-12520
Customer Name                                          Claire Gute
Segment                                                   Consumer
Country                                              United States
City                                                     Henderson
State                                                     Kentucky
Postal Code                                                  42420
Region                                                       South
Product ID                                         FUR-CH-10000454
Category                                                 Furniture
Sub-Category                                                Chairs
Product Name     Hon Deluxe Fabric Upholstered Stacking Chairs,...
Sales                                                       731.94
Quantity                                                         3
Discount                                                       0.0
Profit                                                     219.582
Name: 1, dtype: object

In [ ]:
excel_input.iloc[[0,4,5]]

,Order ID,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,1,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
4,US-2015-108966,5,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
5,CA-2014-115812,6,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694

In [ ]:
#Select a range for rows and columns
#Remember that the ending index is EXCLUSIVE
excel_input.iloc[0:2,1:3]

   Row ID Order Date
0       1 2016-11-08
1       2 2016-11-08

In [ ]:
excel_input.iloc[:10, [0,2,3,5]]

         Order ID Order Date  Ship Date Customer ID
0  CA-2016-152156 2016-11-08 2016-11-11    CG-12520
1  CA-2016-152156 2016-11-08 2016-11-11    CG-12520
2  CA-2016-138688 2016-06-12 2016-06-16    DV-13045
3  US-2015-108966 2015-10-11 2015-10-18    SO-20335
4  US-2015-108966 2015-10-11 2015-10-18    SO-20335
5  CA-2014-115812 2014-06-09 2014-06-14    BH-11710
6  CA-2014-115812 2014-06-09 2014-06-14    BH-11710
7  CA-2014-115812 2014-06-09 2014-06-14    BH-11710
8  CA-2014-115812 2014-06-09 2014-06-14    BH-11710
9  CA-2014-115812 2014-06-09 2014-06-14    BH-11710

### Sorting
- df.sort_values(by=[<column_name or list_of_columns>], ascending=True or False, na_position='first' or 'last')
For sorting the dataframe by a column or list of columns in ascending or descending; can also set the NA in the first or last row.

df.sort_index(ascending=True or False, na_position='last' or 'first')

In [ ]:
#Sorting the dataframe by 'Sales' in ascending order
excel_input.sort_values(by='Sales', ascending=True).head(5)

,Order ID,Row ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4101,US-2017-102288,4102,2017-06-19,2017-06-23,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,77095,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100
9292,CA-2017-124114,9293,2017-03-02,2017-03-02,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,...,76706,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556,1,0.8,-0.9452
8658,CA-2016-168361,8659,2016-06-21,2016-06-25,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,...,60623,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836,1,0.8,-1.3376
4711,CA-2014-112403,4712,2014-03-31,2014-03-31,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,...,19120,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852,1,0.7,-0.5964
2106,US-2014-152723,2107,2014-09-26,2014-09-26,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,...,75150,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876,1,0.8,-1.4016

In [ ]:
#Sorting the dataframe by 2 columns: 'Country' in ascending order and 'Sales' in descending order
#Using loc to select specific columns after sorting
excel_input.sort_values(by=['Country','Sales'], ascending=[True, False]).head(5).loc[:,['Order ID','Country','Sales']]

            Order ID        Country      Sales
2697  CA-2014-145317  United States  22638.480
6826  CA-2016-118689  United States  17499.950
8153  CA-2017-140151  United States  13999.960
2623  CA-2017-127180  United States  11199.968
4190  CA-2017-166709  United States  10499.970