This Halloween dataset contains 85 types of candy. Take a closer look at the columns:
- sugar percentage - The percentile of sugar it falls under within the data set.
- price percentage - The unit price percentile compared to the rest of the set.
- favorite percentage - The overall win percentage according to 269,000 matchups.


Your house is going to be a hit if your candy basket includes the following:
- The 5 candies with the lowest “sugar percentage”. An average trick or treater consumes 7,000 calories worth of candy, so you want to offer some healthy options.
- The 5 candies with the highest “favorite percentage”. Your neighbors know you are a people pleaser!
- The 5 candies with the lowest “price percentage”. The giant tarantula inflatables you bought weren’t cheap, so you need to save some money on the treats.

 

And no peanut or almond candies.
The teal pumpkins at your front door communicate that your candy basked is allergy-friendly. (Did you know that’s a “thing”?)

 

Hint

Make sure to filter out all candies that are not allergy friendly first.

 

Among the 85 types of candy from the dataset, what are the 15 candies to have in your basket?

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/candy.csv')

In [3]:
df.head()

,Candy Name,chocolate,fruity,caramel,peanutyalmondy,crispedricewafer,hard,bar,pluribus,suggar percentage,price percentage,favorite percentage
0,100 Grand,1,0,1,0,1,0,1,0,0.732,0.860,66.972
1,3 Musketeers,1,0,0,0,0,0,1,0,0.604,0.511,67.603
2,One dime,0,0,0,0,0,0,0,0,0.011,0.116,32.261
3,One quarter,0,0,0,0,0,0,0,0,0.011,0.511,46.117
4,Air Heads,0,1,0,0,0,0,0,0,0.906,0.511,52.341

In [ ]:
# Filter out allergen candy
df_safe = df.loc[df['peanutyalmondy'] == 0]
df_safe.loc[df_safe['peanutyalmondy'] != 0] # just checking

Empty DataFrame
Columns: [Candy Name, chocolate, fruity, caramel, peanutyalmondy, crispedricewafer, hard, bar, pluribus, suggar percentage, price percentage, favorite percentage]
Index: []

In [11]:
# lowest sugar percentage
df_sugarfree = df_safe.sort_values(by='suggar percentage', ascending=True).head(5)
df_sugarfree

,Candy Name,chocolate,fruity,caramel,peanutyalmondy,crispedricewafer,hard,bar,pluribus,suggar percentage,price percentage,favorite percentage
3,One quarter,0,0,0,0,0,0,0,0,0.011,0.511,46.117
2,One dime,0,0,0,0,0,0,0,0,0.011,0.116,32.261
12,Chiclets,0,1,0,0,0,0,0,1,0.046,0.325,24.525
30,Lemonhead,0,1,0,0,0,1,0,0,0.046,0.104,39.141
67,Sour Patch Tricksters,0,1,0,0,0,0,0,1,0.069,0.116,52.826

In [14]:
# highest favorite percentage
df_favorites = df_safe.sort_values(by='favorite percentage', ascending=False).head(5)
df_favorites

,Candy Name,chocolate,fruity,caramel,peanutyalmondy,crispedricewafer,hard,bar,pluribus,suggar percentage,price percentage,favorite percentage
79,Twix,1,0,1,0,1,0,1,0,0.546,0.906,81.643
28,Kit Kat,1,0,0,0,1,0,1,0,0.313,0.511,76.769
36,Milky Way,1,0,1,0,0,0,1,0,0.604,0.651,73.100
1,3 Musketeers,1,0,0,0,0,0,1,0,0.604,0.511,67.603
68,Starburst,0,1,0,0,0,0,0,1,0.151,0.220,67.038

In [13]:
# lowest price percentage
df_cheap = df_safe.sort_values(by='price percentage', ascending=True).head(5)
df_cheap

,Candy Name,chocolate,fruity,caramel,peanutyalmondy,crispedricewafer,hard,bar,pluribus,suggar percentage,price percentage,favorite percentage
76,Tootsie Roll Midgies,1,0,0,0,0,0,0,1,0.174,0.011,45.737
48,Pixie Sticks,0,0,0,0,0,0,0,1,0.093,0.023,37.722
15,Fruit Chews,0,1,0,0,0,0,0,1,0.127,0.034,43.089
14,Dum Dums,0,1,0,0,0,1,0,0,0.732,0.034,39.461
69,Strawberry bon bons,0,1,0,0,0,1,0,1,0.569,0.058,34.579

In [15]:
df_shoppinglist = pd.concat([df_sugarfree, df_favorites, df_cheap], ignore_index=True, sort=False)
df_shoppinglist

,Candy Name,chocolate,fruity,caramel,peanutyalmondy,crispedricewafer,hard,bar,pluribus,suggar percentage,price percentage,favorite percentage
0,One quarter,0,0,0,0,0,0,0,0,0.011,0.511,46.117
1,One dime,0,0,0,0,0,0,0,0,0.011,0.116,32.261
2,Chiclets,0,1,0,0,0,0,0,1,0.046,0.325,24.525
3,Lemonhead,0,1,0,0,0,1,0,0,0.046,0.104,39.141
4,Sour Patch Tricksters,0,1,0,0,0,0,0,1,0.069,0.116,52.826
5,Twix,1,0,1,0,1,0,1,0,0.546,0.906,81.643
6,Kit Kat,1,0,0,0,1,0,1,0,0.313,0.511,76.769
7,Milky Way,1,0,1,0,0,0,1,0,0.604,0.651,73.100
8,3 Musketeers,1,0,0,0,0,0,1,0,0.604,0.511,67.603
9,Starburst,0,1,0,0,0,0,0,1,0.151,0.220,67.038
10,Tootsie Roll Midgies,1,0,0,0,0,0,0,1,0.174,0.011,45.737
11,Pixie Sticks,0,0,0,0,0,0,0,1,0.093,0.023,37.722
12,Fruit Chews,0,1,0,0,0,0,0,1,0.127,0.034,43.089
13,Dum Dums,0,1,0,0,0,1,0,0,0.732,0.034,39.461
14,Strawberry bon bons,0,1,0,0,0,1,0,1,0.569,0.058,34.579

In [22]:
# The Alteryx solution stacked the candy data side by side?? Which is absolutely silly, but doing it for fun:
df_sugarfree.reset_index()[['Candy Name', 'suggar percentage', 'price percentage', 'favorite percentage']].reset_index().merge(df_favorites.reset_index()[['Candy Name', 'suggar percentage', 'price percentage', 'favorite percentage']].reset_index(), how='inner', on='index').merge(df_cheap.reset_index()[['Candy Name', 'suggar percentage', 'price percentage', 'favorite percentage']].reset_index(), how='inner', on='index')

,index,Candy Name_x,suggar percentage_x,price percentage_x,favorite percentage_x,Candy Name_y,suggar percentage_y,price percentage_y,favorite percentage_y,Candy Name,suggar percentage,price percentage,favorite percentage
0,0,One quarter,0.011,0.511,46.117,Twix,0.546,0.906,81.643,Tootsie Roll Midgies,0.174,0.011,45.737
1,1,One dime,0.011,0.116,32.261,Kit Kat,0.313,0.511,76.769,Pixie Sticks,0.093,0.023,37.722
2,2,Chiclets,0.046,0.325,24.525,Milky Way,0.604,0.651,73.100,Fruit Chews,0.127,0.034,43.089
3,3,Lemonhead,0.046,0.104,39.141,3 Musketeers,0.604,0.511,67.603,Dum Dums,0.732,0.034,39.461
4,4,Sour Patch Tricksters,0.069,0.116,52.826,Starburst,0.151,0.220,67.038,Strawberry bon bons,0.569,0.058,34.579