A saboteur has infiltrated our team and has been secretly sabotaging operations and eliminating our colleagues. You have been given a dataset from the security department that includes the date, time, room, and personnel logs for an office building where the saboteur is hiding, as well as details of each incident and their corresponding victims.

So far this is the information you have available:

    - The saboteur has eliminated seven victims in total.
    - The saboteur avoids daylight and only works during nighttime (8:00 PM to 6:00 AM).
    - A macro is provided to help you to confront the suspects.
        (Le should be making a script that represents this Alteryx macro.)

    The saboteur has a fake name, so once you discover who the person is, you should determine their real name.
        Hint: The real name is the employee’s name spelled in reverse order (no spaces).

Your output should include both the saboteur's fake name and real name.

For your reference, we have included an additional hint within the workflow that contains the list of suspects.

In [3]:
import pandas as pd
from datetime import datetime

In [4]:
df = pd.read_csv('data/Saboteur_440.csv')

In [5]:
# data is only 50 rows
df.head(50)

,Date,Time,Room,Personnel Logs,Incident,Victim
0,9/01/2022,9:18 PM,Office,"Olga Paggitt, Kurtis Manston, Brigitta Breddy,...",NaN,NaN
1,8/02/2022,6:37 PM,Kitchen,"Brigitta Breddy, Martica Eitter",NaN,NaN
2,9/02/2022,4:21 AM,Entrance,"Waverley Keddie, Kristen Schofield",NaN,NaN
3,11/02/2022,10:55 PM,Kitchen,"Dorolice Matthews, Prudence Slaight, Leta Tonn...",NaN,NaN
4,10/03/2022,12:39 AM,Toilet,"Ferrell Yakunikov, Marjory Greswell",NaN,NaN
5,11/03/2022,6:34 AM,Kitchen,"Ferrell Yakunikov, Waverley Keddie, Kristen Sc...",NaN,NaN
6,8/04/2022,1:31 AM,Lounge,"Gareth Lovie, Dorolice Matthews, Arie Mum, Ali...",Murder,Erek Sivorn
7,11/04/2022,2:24 AM,Garage,"Ferrell Yakunikov, Waverley Keddie",NaN,NaN
8,9/05/2022,8:14 PM,Balcony,"Jessie Lages, Tamiko Tomasoni",NaN,NaN
9,10/05/2022,2:42 AM,Toilet,"Edythe Rief, Kristopher Cannaway, Alexandra Ma...",Murder,Eustacia Concannon
10,8/06/2022,5:42 PM,Toilet,"Alisun Gauge, Liuka Deesly, Cully McKirdy, Olg...",NaN,NaN
11,10/07/2022,1:26 PM,Office,"Orella Kubczak, Ferrell Yakunikov",NaN,NaN
12,10/07/2022,5:35 AM,Basement,"Liuka Deesly, Cully McKirdy, Olga Paggitt, Ell...",NaN,NaN
13,11/07/2022,6:09 PM,Office,"Waverley Keddie, Niven Caville, Wilma Grioli",NaN,NaN
14,10/08/2022,10:06 PM,Kitchen,"Dorolice Matthews, Arie Mum, Alisun Gauge",NaN,NaN
15,11/08/2022,10:55 AM,Yoga Room,"Kurtis Manston, Brigitta Breddy, Martica Eitte...",NaN,NaN
16,8/09/2022,7:12 PM,Kitchen,"Waverley Keddie, Mario Sewley",NaN,NaN
17,8/09/2022,9:40 PM,Entrance,"Olga Paggitt, Elle Banna, Martguerita Bulstrod...",Murder,Kort Gleeson
18,9/10/2022,1:56 AM,Yoga Room,"Ferrell Yakunikov, Wilma Grioli",NaN,NaN
19,8/11/2022,6:47 PM,Balcony,"Ferrell Yakunikov, Marjory Greswell",NaN,NaN
20,10/14/2022,4:41 AM,Office,"Dorolice Matthews, Arie Mum, Alisun Gauge, Liu...",Murder,Creigh Alesio
21,10/15/2022,1:55 PM,Basement,"Alisun Gauge, Liuka Deesly, Cully McKirdy, Olg...",NaN,NaN
22,10/19/2022,12:02 PM,Office,"Jessie Lages, Tamiko Tomasoni",NaN,NaN
23,10/23/2022,12:13 PM,Kitchen,"Kristen Schofield, Allen Winspear",NaN,NaN
24,10/23/2022,7:13 AM,Toilet,"Meggy Ditts, Marjory Greswell",NaN,NaN
25,10/26/2022,7:47 AM,Yoga Room,"Cully McKirdy, Dorolice Matthews",NaN,NaN
26,10/27/2022,3:18 PM,Garage,"Liuka Deesly, Mada Pirolini",NaN,NaN
27,10/31/2022,7:10 AM,Garage,"Jessie Lages, Tamiko Tomasoni, Martica Eitter,...",NaN,NaN
28,10/31/2022,7:43 AM,Garage,"Kristen Schofield, Cully McKirdy, Olga Paggitt",NaN,NaN
29,11/14/2022,3:46 PM,Basement,"Liuka Deesly, Mada Pirolini, Dorolice Matthew...",NaN,NaN
30,11/16/2022,3:48 AM,Kitchen,"Leta Tonn, Elle Banna, Arie Mum, Alisun Gauge",NaN,NaN
31,11/16/2022,5:38 PM,Basement,"Allen Winspear, Coleen Genders",NaN,NaN
32,11/22/2022,6:19 AM,Toilet,"Waverley Keddie, Marjory Greswell",NaN,NaN
33,11/24/2022,10:17 PM,Balcony,"Traci Eland, iuka Deesly, Mada Pirolini, Nero...",NaN,NaN
34,11/24/2022,10:28 PM,Toilet,"Kurtis Manston, Brigitta Breddy, Cully McKirdy...",Murder,Jacquelynn Thowes
35,11/27/2022,6:58 PM,Kitchen,"Nero Simonite, Jessie Lages, Juliet Groarty",NaN,NaN
36,8/15/2022,4:18 AM,Entrance,"Marjory Greswell, Allen Winspear",NaN,NaN
37,8/15/2022,11:07 PM,Basement,"Martica Eitter, Nero Simonite, Jessie Lages",NaN,NaN
38,8/16/2022,8:48 AM,Kitchen,"Alisun Gauge, Liuka Deesly, Cully McKirdy, Olg...",NaN,NaN
39,8/16/2022,3:35 PM,Garage,"Liuka Deesly, Mada Pirolini, Nero Simonite, J...",NaN,NaN
40,8/30/2022,2:57 AM,Kitchen,"Berry Clementi, Leta Tonn, Mada Pirolini, Doro...",Murder,Perceval Begg
41,8/31/2022,6:11 AM,Toilet,"Loren Torricina, Marjory Greswell",NaN,NaN
42,9/14/2022,12:11 AM,Garage,"Elle Banna, Martica Eitter, Nero Simonite, Jes...",Murder,Essy Keppie
43,9/14/2022,4:55 PM,Basement,"Prudence Slaight, Marjory Greswell",NaN,NaN
44,9/14/2022,11:47 AM,Balcony,"Brigitta Breddy, Martica Eitter",NaN,NaN
45,9/14/2022,11:58 AM,Toilet,"Meggy Ditts, Marjory Greswell",NaN,NaN
46,9/22/2022,6:55 AM,Entrance,"Essy Keppie, Martica Eitter, Nero Simonite, Cu...",NaN,NaN
47,9/23/2022,5:18 AM,Yoga Room,"Leta Tonn, Dorolice Matthews",NaN,NaN
48,9/28/2022,6:21 PM,Kitchen,"Marjory Greswell, Meggy Ditts",NaN,NaN
49,9/29/2022,6:41 AM,Office,"Kurtis Manston, Brigitta Breddy, Martica Eitte...",NaN,NaN

In [6]:
df.dtypes

Date              object
Time              object
Room              object
Personnel Logs    object
Incident          object
Victim            object
dtype: object

In [7]:
df['Time'] = pd.to_datetime(df['Time']).dt.time

C:\Users\LexDevlin\AppData\Local\Temp\ipykernel_11836\3728333153.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(df['Time']).dt.time

In [8]:
df.head()

,Date,Time,Room,Personnel Logs,Incident,Victim
0,9/01/2022,21:18:00,Office,"Olga Paggitt, Kurtis Manston, Brigitta Breddy,...",NaN,NaN
1,8/02/2022,18:37:00,Kitchen,"Brigitta Breddy, Martica Eitter",NaN,NaN
2,9/02/2022,04:21:00,Entrance,"Waverley Keddie, Kristen Schofield",NaN,NaN
3,11/02/2022,22:55:00,Kitchen,"Dorolice Matthews, Prudence Slaight, Leta Tonn...",NaN,NaN
4,10/03/2022,00:39:00,Toilet,"Ferrell Yakunikov, Marjory Greswell",NaN,NaN

In [9]:
# Filter to hours between 8pm-6am
df_filtered = df[(df['Time'] >= pd.to_datetime('20:00:00').time()) | (df['Time'] <= pd.to_datetime('06:00:00').time())]

In [10]:
# Showing all incidents between 10pm and 6am. Not like there were any murders outside this timeframe anyway...
df_filtered

,Date,Time,Room,Personnel Logs,Incident,Victim
0,9/01/2022,21:18:00,Office,"Olga Paggitt, Kurtis Manston, Brigitta Breddy,...",NaN,NaN
2,9/02/2022,04:21:00,Entrance,"Waverley Keddie, Kristen Schofield",NaN,NaN
3,11/02/2022,22:55:00,Kitchen,"Dorolice Matthews, Prudence Slaight, Leta Tonn...",NaN,NaN
4,10/03/2022,00:39:00,Toilet,"Ferrell Yakunikov, Marjory Greswell",NaN,NaN
6,8/04/2022,01:31:00,Lounge,"Gareth Lovie, Dorolice Matthews, Arie Mum, Ali...",Murder,Erek Sivorn
7,11/04/2022,02:24:00,Garage,"Ferrell Yakunikov, Waverley Keddie",NaN,NaN
8,9/05/2022,20:14:00,Balcony,"Jessie Lages, Tamiko Tomasoni",NaN,NaN
9,10/05/2022,02:42:00,Toilet,"Edythe Rief, Kristopher Cannaway, Alexandra Ma...",Murder,Eustacia Concannon
12,10/07/2022,05:35:00,Basement,"Liuka Deesly, Cully McKirdy, Olga Paggitt, Ell...",NaN,NaN
14,10/08/2022,22:06:00,Kitchen,"Dorolice Matthews, Arie Mum, Alisun Gauge",NaN,NaN
17,8/09/2022,21:40:00,Entrance,"Olga Paggitt, Elle Banna, Martguerita Bulstrod...",Murder,Kort Gleeson
18,9/10/2022,01:56:00,Yoga Room,"Ferrell Yakunikov, Wilma Grioli",NaN,NaN
20,10/14/2022,04:41:00,Office,"Dorolice Matthews, Arie Mum, Alisun Gauge, Liu...",Murder,Creigh Alesio
30,11/16/2022,03:48:00,Kitchen,"Leta Tonn, Elle Banna, Arie Mum, Alisun Gauge",NaN,NaN
33,11/24/2022,22:17:00,Balcony,"Traci Eland, iuka Deesly, Mada Pirolini, Nero...",NaN,NaN
34,11/24/2022,22:28:00,Toilet,"Kurtis Manston, Brigitta Breddy, Cully McKirdy...",Murder,Jacquelynn Thowes
36,8/15/2022,04:18:00,Entrance,"Marjory Greswell, Allen Winspear",NaN,NaN
37,8/15/2022,23:07:00,Basement,"Martica Eitter, Nero Simonite, Jessie Lages",NaN,NaN
40,8/30/2022,02:57:00,Kitchen,"Berry Clementi, Leta Tonn, Mada Pirolini, Doro...",Murder,Perceval Begg
42,9/14/2022,00:11:00,Garage,"Elle Banna, Martica Eitter, Nero Simonite, Jes...",Murder,Essy Keppie
47,9/23/2022,05:18:00,Yoga Room,"Leta Tonn, Dorolice Matthews",NaN,NaN

In [11]:
# Plan is to split to rows every person who was present for where the incident was murder
df_filtered2 = df_filtered[df_filtered['Incident'] == 'Murder']

In [12]:
df_filtered2

,Date,Time,Room,Personnel Logs,Incident,Victim
6,8/04/2022,01:31:00,Lounge,"Gareth Lovie, Dorolice Matthews, Arie Mum, Ali...",Murder,Erek Sivorn
9,10/05/2022,02:42:00,Toilet,"Edythe Rief, Kristopher Cannaway, Alexandra Ma...",Murder,Eustacia Concannon
17,8/09/2022,21:40:00,Entrance,"Olga Paggitt, Elle Banna, Martguerita Bulstrod...",Murder,Kort Gleeson
20,10/14/2022,04:41:00,Office,"Dorolice Matthews, Arie Mum, Alisun Gauge, Liu...",Murder,Creigh Alesio
34,11/24/2022,22:28:00,Toilet,"Kurtis Manston, Brigitta Breddy, Cully McKirdy...",Murder,Jacquelynn Thowes
40,8/30/2022,02:57:00,Kitchen,"Berry Clementi, Leta Tonn, Mada Pirolini, Doro...",Murder,Perceval Begg
42,9/14/2022,00:11:00,Garage,"Elle Banna, Martica Eitter, Nero Simonite, Jes...",Murder,Essy Keppie

In [13]:
df_exploded = df_filtered2.assign(names=df_filtered2['Personnel Logs'].str.split(',\s*')).explode('names')

In [14]:
df_exploded

,Date,Time,Room,Personnel Logs,Incident,Victim,names
6,8/04/2022,01:31:00,Lounge,"Gareth Lovie, Dorolice Matthews, Arie Mum, Ali...",Murder,Erek Sivorn,Gareth Lovie
6,8/04/2022,01:31:00,Lounge,"Gareth Lovie, Dorolice Matthews, Arie Mum, Ali...",Murder,Erek Sivorn,Dorolice Matthews
6,8/04/2022,01:31:00,Lounge,"Gareth Lovie, Dorolice Matthews, Arie Mum, Ali...",Murder,Erek Sivorn,Arie Mum
6,8/04/2022,01:31:00,Lounge,"Gareth Lovie, Dorolice Matthews, Arie Mum, Ali...",Murder,Erek Sivorn,Alisun Gauge
6,8/04/2022,01:31:00,Lounge,"Gareth Lovie, Dorolice Matthews, Arie Mum, Ali...",Murder,Erek Sivorn,Liuka Deesly
...,...,...,...,...,...,...,...
42,9/14/2022,00:11:00,Garage,"Elle Banna, Martica Eitter, Nero Simonite, Jes...",Murder,Essy Keppie,Liuka Deesly
42,9/14/2022,00:11:00,Garage,"Elle Banna, Martica Eitter, Nero Simonite, Jes...",Murder,Essy Keppie,Cully McKirdy
42,9/14/2022,00:11:00,Garage,"Elle Banna, Martica Eitter, Nero Simonite, Jes...",Murder,Essy Keppie,Leta Tonn
42,9/14/2022,00:11:00,Garage,"Elle Banna, Martica Eitter, Nero Simonite, Jes...",Murder,Essy Keppie,Mada Pirolini
42,9/14/2022,00:11:00,Garage,"Elle Banna, Martica Eitter, Nero Simonite, Jes...",Murder,Essy Keppie,Olga Paggitt

In [18]:
df_suspects = df_exploded.groupby('names', as_index=False).agg(incident_count=('names', 'count'))

In [19]:
df_suspects

                    names  incident_count
0        Alexandra Malins               1
1            Alisun Gauge               7
2                Arie Mum               7
3          Berry Clementi               1
4         Brigitta Breddy               1
5           Cully McKirdy               7
6       Dorolice Matthews               6
7             Edythe Rief               1
8              Elle Banna               7
9            Gareth Lovie               1
10           Jessie Lages               7
11    Kristopher Cannaway               1
12         Kurtis Manston               1
13              Leta Tonn               7
14           Liuka Deesly               7
15          Mada Pirolini               7
16  Martguerita Bulstrode               1
17         Martica Eitter               7
18          Nero Simonite               7
19           Olga Paggitt               7
20        Tamiko Tomasoni               7